version: '2'
services:
  lazyblob-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/lazyblob/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lazyblob
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
